### ISSUE TITLE
.DS_Store is present in styled-jsx@3.2.4 as packaged on npm

### ISSUE THREAD

**Issue by ChALkeR** [vercel/styled-jsx#612] opened 2020-01-07 20:21 UTC
To reproduce:
```console
$ npm pack styled-jsx@3.2.4
npm notice
npm notice 📦  styled-jsx@3.2.4
npm notice === Tarball Contents ===
npm notice 6.1kB  dist/.DS_Store
npm notice 599B   dist/_constants.js
npm notice 22.3kB dist/_utils.js
npm notice 8.2kB  dist/babel-external.js
npm notice 46B    babel-test.js
npm notice 753B   dist/babel-test.js
npm notice 41B    babel.js
npm notice 10.4kB dist/babel.js
npm notice 469B   css.js
npm notice 4.4kB  dist/macro.js
npm notice 41B    macro.js
npm notice 1.1kB  dist/server.js
npm notice 42B    server.js
npm notice 3.0kB  dist/lib/style-transform.js
npm notice 56B    lib/style-transform.js
npm notice 2.2kB  dist/style.js
npm notice 41B    style.js
npm notice 7.1kB  dist/stylesheet-registry.js
npm notice 8.3kB  dist/lib/stylesheet.js
npm notice 51B    lib/stylesheet.js
npm notice 1.5kB  dist/webpack.js
npm notice 65B    webpack.js
npm notice 2.4kB  package.json
npm notice 1.1kB  license.md
npm notice 29.6kB readme.md
npm notice === Tarball Details ===
npm notice name:          styled-jsx
npm notice version:       3.2.4
npm notice filename:      styled-jsx-3.2.4.tgz
npm notice package size:  29.7 kB
npm notice unpacked size: 109.9 kB
npm notice shasum:        cbcdedcfb81d717fd355c4a0d8443f8e74527b60
npm notice integrity:     sha512-UMclQzI1lss38[...]tv+6K/553ANdg==
npm notice total files:   25
npm notice
$ tar -xf styled-jsx-3.2.4.tgz
$ find package -name .DS_Store
package/dist/.DS_Store
```

Ideally, it should be ignored via `files` option, `.gitignore`, or `.npmignore`.

Also -- I don't see a 3.2.4 commit or tag on GitHub that would correspond to the 3.2.4 version distributed via npm?

**Comment by giuseppeg** [comment] 2020-02-23 09:59
@ChALkeR thanks for spotting this! Could you submit a PR to fix it?

**Comment by urltrn13** [comment] 2020-04-12 01:42
Duplicate of #

**Comment by Ravichandra-C** [comment] 2021-09-04 14:03
@giuseppeg Is this issue still up for grabs?

**Comment by huozhi** [comment] 2021-09-04 14:18
should be good to close since it's not present in the latest version. thanks for reminding

**Closed by huozhi** 2021-09-04 14:18 UTC
Labels: help wanted, good first issue
