### ISSUE TITLE
CSS Preprocessing with SWC

### ISSUE THREAD

**Issue by mattjennings** [vercel/styled-jsx#782] opened 2022-02-10 19:58 UTC
#### Do you want to request a _feature_ or report a _bug_?

Feature

#### What is the current behavior?

It seems there is currently no support for plugins when using SWC with Next.js. Are there any plans for this? I'd really like to setup PostCSS, but of course it's only available as a babel plugin.

#### What is the expected behavior?

Plugin system to allow CSS preprocessing

#### Environment (include versions)

- Version of styled-jsx (or next.js if it's being used): Next.js
- Browser: Chrome
- OS: macOS

#### Did this work in previous versions?

Yes, plugin system is available with Babel

**Comment by KarthikeyanRanasthala** [comment] 2022-03-04 06:55
Bump!

**Comment by tettoffensive** [comment] 2022-03-17 18:17
Seems strange that there isn't support since this is a Vercel project and Next.js is now using SWC. I personally want to be able to use scss syntax in my project.

**Comment by huozhi** [comment] 2022-03-18 11:56
cc @kdy1 @kwonoj

**Comment by kdy1** [comment] 2022-03-18 12:00
Do you mean a rust-based one, or postcss?

**Comment by Somiona** [comment] 2022-03-30 20:32
Upvote, the current example for enabling styled jsx plugins is by using it with babel, and there's no clear instruction of how to configure it to work with swc.

**Comment by dayvista** [comment] 2022-04-08 12:55
PostCSS support for SWC would enable Tailwind CSS usage, like the [`@apply` directive](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply).

**Comment by stef7** [comment] 2022-05-21 04:30
Bumping too... Still no way to use PostCSS + Styled JSX with SWC 😞

**Comment by jacquescrocker** [comment] 2022-07-11 19:59
This is definitely blocking my usage of SWC. I can't imagine having to go back to plain CSS for all my components... that seems so incredibly backwards.

**Comment by huozhi** [comment] 2022-07-16 22:15
https://swc.rs/docs/configuration/compilation#jscexperimentalplugins might be sth you're looking for

**Comment by Garett-MacGowan** [comment] 2022-09-03 19:49
> https://swc.rs/docs/configuration/compilation#jscexperimentalplugins might be sth you're looking for

I'm having a hard time using that plugin. As far as I can tell, .swcrc doesn't load in Next.js. As such, i've tried adding the plugin to the experimental swcPlugins section in next.config.js. I've run `npm install @swc/plugin-styled-jsx` and confirmed it exists in node-modules.

```
experimental: {
  swcPlugins: [
    ['@swc/plugin-styled-jsx', {}]
  ]
}
```
The above configuration throws "Failed to create plugin instance"

Any insights would be appreciated. Would like to avoid babel + styled-jsx-plugin-postcss.

**Comment by huozhi** [comment] 2022-09-03 21:57
@Garett-MacGowan if you’re using nextjs, you don’t need to configure swcrc for styled-jsx. Which nextjs version are you having issue with?

**Comment by Venipa** [comment] 2022-09-08 10:47
@huozhi we actually do need to since tailwind isnt available in styled-jsx

**Comment by huozhi** [comment] 2022-09-08 11:43
I would say this is more like a limitation to swc while supporting various usage cases. swc compilation for next.js (next-swc) can have native and wasm bindings to run in different scenarios. Supporting many pre-processing plugins which are depending on node.js (like sass) would be a problem for wasm build of next-swc. Also it could have a performance limitation which is opposite to the purpose of having swc compilation.

At the moment we don't have an nice solution to handle it in both ways, going to close this issue for now.

**Closed by huozhi** 2022-09-08 11:43 UTC

**Comment by dzcpy** [comment] 2023-08-04 05:47
> 

Have you got it working with style-jsx + tailwind(postcss)?

**Comment by dzcpy** [comment] 2023-08-04 05:48
> @huozhi we actually do need to since tailwind isnt available in styled-jsx without configuring postcss
> 
> ![image](https://user-images.githubusercontent.com/17952364/189103891-6c971c32-d74c-4632-b677-5e3b0597fc37.png)
> 
> my current .swcrc config
> 
> ```json
> {
>   "$schema": "https://json.schemastore.org/swcrc",
>   "jsc": {
>     "experimental": {
>       "plugins": [
>         [
>           "@swc/plugin-styled-jsx",
>           {
>             "plugins": [
>               "@styled-jsx/plugin-sass",
>               "styled-jsx-plugin-postcss"
>             ]
>           }
>         ]
>       ]
>     }
>   }
> }
> ```

Have you got it working with style-jsx + tailwind(postcss)?

**Comment by Venipa** [comment] 2024-09-14 20:37
so any updates on this? cuz this is bad:
![image](https://github.com/user-attachments/assets/b31c6031-35ce-475a-8514-90ef924bef7f)
